/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lab4;

/**
 *
 * @author cleme
 */
public class Vent3 extends javax.swing.JFrame {

    /**
     * Creates new form prueba_interfaz
     */
    public Vent3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        terminar_v1 = new javax.swing.JButton();
        game_v5 = new javax.swing.JButton();
        players_label = new javax.swing.JLabel();
        players_pane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        add_player = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 183, 176));
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setPreferredSize(new java.awt.Dimension(800, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        terminar_v1.setBackground(new java.awt.Color(255, 239, 255));
        terminar_v1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        terminar_v1.setText("TERMINAR");
        terminar_v1.setFocusable(false);
        background.add(terminar_v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, -1));

        game_v5.setBackground(new java.awt.Color(255, 239, 255));
        game_v5.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        game_v5.setText("INICIAR JUEGO");
        game_v5.setFocusable(false);
        background.add(game_v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        players_label.setBackground(new java.awt.Color(255, 183, 176));
        players_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        players_label.setForeground(new java.awt.Color(255, 239, 255));
        players_label.setText("Jugadores:");
        background.add(players_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 239, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(8);
        jTextArea1.setBorder(null);
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setHighlighter(null);
        players_pane.setViewportView(jTextArea1);

        background.add(players_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        add_player.setBackground(new java.awt.Color(255, 239, 255));
        add_player.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        add_player.setText("Agregar jugador");
        add_player.setFocusable(false);
        add_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_playerActionPerformed(evt);
            }
        });
        background.add(add_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_playerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_player;
    private javax.swing.JPanel background;
    private javax.swing.JButton game_v5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel players_label;
    private javax.swing.JScrollPane players_pane;
    private javax.swing.JButton terminar_v1;
    // End of variables declaration//GEN-END:variables
}
