/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lab4;
import lab3.controlador.*;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;

/**
 *
 * @author cleme
 */
public class Vent2 extends javax.swing.JFrame {

    /**
     * Creates new form prueba_interfaz
     */
    public Vent2() {
        initComponents();
    }
    
    static Controlador controlador = new Controlador();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Volver_v1 = new javax.swing.JButton();
        Crear_v3 = new javax.swing.JButton();
        maxC_field = new javax.swing.JTextField();
        maxC_label = new javax.swing.JLabel();
        mode_field = new javax.swing.JTextField();
        numE_label = new javax.swing.JLabel();
        nPlayers_field = new javax.swing.JTextField();
        nPlayers_label = new javax.swing.JLabel();
        mode_label = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        Separator3 = new javax.swing.JSeparator();
        Separator4 = new javax.swing.JSeparator();
        qmark4 = new javax.swing.JLabel();
        qmark1 = new javax.swing.JLabel();
        qmark2 = new javax.swing.JLabel();
        qmark3 = new javax.swing.JLabel();
        numE_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear juego");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 183, 176));
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setFocusable(false);
        background.setPreferredSize(new java.awt.Dimension(800, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver_v1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        Volver_v1.setText("VOLVER");
        Volver_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_v1ActionPerformed(evt);
            }
        });
        background.add(Volver_v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 140, -1));

        Crear_v3.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        Crear_v3.setText("CREAR");
        Crear_v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_v3ActionPerformed(evt);
            }
        });
        background.add(Crear_v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 140, -1));

        maxC_field.setBackground(new java.awt.Color(255, 239, 255));
        maxC_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maxC_field.setToolTipText("Ingrese el número de cartas con el que desea jugar");
        maxC_field.setBorder(null);
        maxC_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxC_fieldActionPerformed(evt);
            }
        });
        background.add(maxC_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 190, 30));

        maxC_label.setBackground(new java.awt.Color(255, 183, 176));
        maxC_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maxC_label.setForeground(new java.awt.Color(255, 239, 255));
        maxC_label.setText("Tamaño del mazo:");
        background.add(maxC_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        mode_field.setBackground(new java.awt.Color(255, 239, 255));
        mode_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mode_field.setToolTipText("");
        mode_field.setBorder(null);
        mode_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode_fieldActionPerformed(evt);
            }
        });
        background.add(mode_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 190, 30));

        numE_label.setBackground(new java.awt.Color(255, 183, 176));
        numE_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numE_label.setForeground(new java.awt.Color(255, 239, 255));
        numE_label.setText("Figuras por carta:");
        background.add(numE_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        nPlayers_field.setBackground(new java.awt.Color(255, 239, 255));
        nPlayers_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nPlayers_field.setToolTipText("");
        nPlayers_field.setBorder(null);
        nPlayers_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPlayers_fieldActionPerformed(evt);
            }
        });
        background.add(nPlayers_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 190, 30));

        nPlayers_label.setBackground(new java.awt.Color(255, 183, 176));
        nPlayers_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nPlayers_label.setForeground(new java.awt.Color(255, 239, 255));
        nPlayers_label.setText("Número de jugadores:");
        background.add(nPlayers_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        mode_label.setBackground(new java.awt.Color(255, 183, 176));
        mode_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mode_label.setForeground(new java.awt.Color(255, 239, 255));
        mode_label.setText("Modo de juego:");
        background.add(mode_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));
        background.add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 130, 10));
        background.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 130, 10));
        background.add(Separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 130, 10));
        background.add(Separator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 130, 10));

        qmark4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/q_mark.png"))); // NOI18N
        qmark4.setToolTipText("Escoja su modo de juego.");
        background.add(qmark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 40, 40));

        qmark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/q_mark.png"))); // NOI18N
        qmark1.setToolTipText("Ingresa el número de jugadores para tu partida.");
        background.add(qmark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 40, 40));

        qmark2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/q_mark.png"))); // NOI18N
        qmark2.setToolTipText("Ingrese el tamaño del mazo con el que se desea jugar. En csao de querer un mazo completo, ingresar -1.");
        background.add(qmark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 40, 40));

        qmark3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/q_mark.png"))); // NOI18N
        qmark3.setToolTipText("Ingrese el número de figuras que aparecerán en cada carta.");
        background.add(qmark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 40, 40));

        numE_field.setBackground(new java.awt.Color(255, 239, 255));
        numE_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numE_field.setToolTipText("");
        numE_field.setBorder(null);
        numE_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numE_fieldActionPerformed(evt);
            }
        });
        background.add(numE_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_v1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Vent1 v1 = new Vent1();
        v1.setVisible(true);
    }//GEN-LAST:event_Volver_v1ActionPerformed

    private void nPlayers_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPlayers_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPlayers_fieldActionPerformed

    private void maxC_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxC_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxC_fieldActionPerformed

    private void Crear_v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_v3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        controlador.crear_juego(Integer.parseInt(nPlayers_field.getText()), 
                Integer.parseInt(maxC_field.getText()),
                Integer.parseInt(numE_field.getText()),
                Integer.parseInt(mode_field.getText()));
        Vent3 v3 = new Vent3();
        v3.Jugadores_display1.setText(controlador.visualizar_Jugadores());
        v3.elements_display.setText(controlador.visualizar_Elementos());
        v3.setVisible(true);
    }//GEN-LAST:event_Crear_v3ActionPerformed

    private void mode_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mode_fieldActionPerformed

    private void numE_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numE_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numE_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_v3;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JButton Volver_v1;
    private javax.swing.JPanel background;
    public static javax.swing.JTextField maxC_field;
    private javax.swing.JLabel maxC_label;
    public static javax.swing.JTextField mode_field;
    private javax.swing.JLabel mode_label;
    public static javax.swing.JTextField nPlayers_field;
    private javax.swing.JLabel nPlayers_label;
    public static javax.swing.JTextField numE_field;
    private javax.swing.JLabel numE_label;
    private javax.swing.JLabel qmark1;
    private javax.swing.JLabel qmark2;
    private javax.swing.JLabel qmark3;
    private javax.swing.JLabel qmark4;
    // End of variables declaration//GEN-END:variables
}
