/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lab4;
import com.lab4.Vent2;
import lab3.controlador.*;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;

/**
 *
 * @author cleme
 */
public class Vent3 extends javax.swing.JFrame {

    /**
     * Tercera ventana del programa.
     * initComponents() Inicializa los componentes del JFrame.
     */
    public Vent3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        terminar_v1 = new javax.swing.JButton();
        game_v5 = new javax.swing.JButton();
        numE_label2 = new javax.swing.JLabel();
        add_player = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        elements_display = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jugadores_display1 = new javax.swing.JTextPane();
        players_label1 = new javax.swing.JLabel();
        numE_label1 = new javax.swing.JLabel();
        numE_label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar jugadores");
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 183, 176));
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setPreferredSize(new java.awt.Dimension(800, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        terminar_v1.setBackground(new java.awt.Color(255, 239, 255));
        terminar_v1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        terminar_v1.setText("TERMINAR");
        terminar_v1.setFocusable(false);
        terminar_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminar_v1ActionPerformed(evt);
            }
        });
        background.add(terminar_v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 160, -1));

        game_v5.setBackground(new java.awt.Color(255, 239, 255));
        game_v5.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        game_v5.setText("INICIAR JUEGO");
        game_v5.setFocusable(false);
        background.add(game_v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        numE_label2.setBackground(new java.awt.Color(255, 183, 176));
        numE_label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numE_label2.setForeground(new java.awt.Color(255, 239, 255));
        numE_label2.setText("del mazo:");
        background.add(numE_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        add_player.setBackground(new java.awt.Color(255, 239, 255));
        add_player.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        add_player.setText("Agregar jugador");
        add_player.setFocusable(false);
        add_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_playerActionPerformed(evt);
            }
        });
        background.add(add_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        elements_display.setEditable(false);
        jScrollPane1.setViewportView(elements_display);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 340, 130));

        Jugadores_display1.setEditable(false);
        jScrollPane2.setViewportView(Jugadores_display1);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, 130));

        players_label1.setBackground(new java.awt.Color(255, 183, 176));
        players_label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        players_label1.setForeground(new java.awt.Color(255, 239, 255));
        players_label1.setText("Jugadores:");
        background.add(players_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        numE_label1.setBackground(new java.awt.Color(255, 183, 176));
        numE_label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numE_label1.setForeground(new java.awt.Color(255, 239, 255));
        numE_label1.setText("Elementos");
        background.add(numE_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        numE_label3.setBackground(new java.awt.Color(255, 183, 176));
        numE_label3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numE_label3.setForeground(new java.awt.Color(255, 239, 255));
        numE_label3.setText("del mazo:");
        background.add(numE_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Operación del botón AGREGAR JUGADOR.
     * @param evt 
     * Oculta Vent3 e inicializa Vent4.
     */
    private void add_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_playerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Vent4 v4 = new Vent4();
        v4.setVisible(true);
    }//GEN-LAST:event_add_playerActionPerformed

    /**
     * Operación del botón TERMINAR.
     * @param evt 
     * Oculta Vent3 e inicializa Vent1.
     */
    private void terminar_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminar_v1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Vent1 v1 = new Vent1();
        v1.setVisible(true);
    }//GEN-LAST:event_terminar_v1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vent3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane Jugadores_display1;
    private javax.swing.JButton add_player;
    private javax.swing.JPanel background;
    public javax.swing.JTextPane elements_display;
    private javax.swing.JButton game_v5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numE_label1;
    private javax.swing.JLabel numE_label2;
    private javax.swing.JLabel numE_label3;
    private javax.swing.JLabel players_label1;
    private javax.swing.JButton terminar_v1;
    // End of variables declaration//GEN-END:variables
}
